/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['[_nghost-%COMP%] {\r\n  padding-top: 25px;\r\n}\r\n\r\nmd-table[_ngcontent-%COMP%] {\r\n  overflow: auto;\r\n  max-height: 830px;\r\n  max-width: 1400px;\r\n  margin: auto;\r\n}'];
//# sourceMappingURL=queued.component.scss.shim.ngstyle.js.map