/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['md-nav-list[_ngcontent-%COMP%] {\r\n  flex-direction: row;\r\n  display: flex;\r\n}'];
//# sourceMappingURL=toolbar.component.scss.shim.ngstyle.js.map