/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['[_nghost-%COMP%] {\r\n  padding-top: 25px;\r\n}\r\n\r\nmd-table[_ngcontent-%COMP%] {\r\n  overflow: auto;\r\n  max-height: 830px;\r\n  max-width: 1400px;\r\n  margin: auto;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWxleC9Db2RlL0phdmFTY3JpcHQvdHh0ci5pby9zcmMvYXBwL3RleHRzL3R5cGUvdHlwZS5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9BbGV4L0NvZGUvSmF2YVNjcmlwdC90eHRyLmlvL3NyYy9hcHAvdGV4dHMvdHlwZS90eXBlLmNvbXBvbmVudC5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
