/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/core/core.module';
import * as i2 from '../../../node_modules/@angular/material/typings/index.ngfactory';
import * as i3 from '@angular/common/http';
import * as i4 from '@angular/common';
import * as i5 from '../../../../src/app/core/http.interceptors';
import * as i6 from '@angular/forms';
import * as i7 from '@angular/cdk/bidi';
import * as i8 from '@angular/platform-browser';
import * as i9 from '@angular/cdk/platform';
import * as i10 from '@angular/cdk/scrolling';
import * as i11 from '@angular/cdk/overlay';
import * as i12 from '@angular/material';
import * as i13 from '@angular/cdk/observers';
import * as i14 from '@angular/cdk/a11y';
import * as i15 from '@angular/http';
import * as i16 from '@angular/flex-layout/media-query/match-media';
import * as i17 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as i18 from '@angular/flex-layout/media-query/breakpoints/break-points';
import * as i19 from '@angular/flex-layout/media-query/media-monitor';
import * as i20 from '@angular/flex-layout/media-query/observable-media-service';
import * as i21 from '../../../../src/app/core/services/auth.service';
import * as i22 from '@angular/router';
import * as i23 from '@angular/cdk/portal';
import * as i24 from '@angular/cdk/table';
import * as i25 from '@angular/flex-layout/media-query/_module';
import * as i26 from '@angular/flex-layout/flexbox/_module';
import * as i27 from '../../../../src/app/core/shared.module';
export const CoreModuleNgFactory:i0.NgModuleFactory<i1.CoreModule> = i0.ɵcmf(i1.CoreModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.MdDialogContainerNgFactory,i2.MdDatepickerContentNgFactory,i2.TooltipComponentNgFactory,
              i2.MdSnackBarContainerNgFactory,i2.SimpleSnackBarNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i3.HttpXsrfTokenExtractor,i3.ɵg,[i4.DOCUMENT,
          i0.PLATFORM_ID,i3.ɵe]),i0.ɵmpd(4608,i3.ɵh,i3.ɵh,[i3.HttpXsrfTokenExtractor,
          i3.ɵf]),i0.ɵmpd(5120,i3.HTTP_INTERCEPTORS,(p0_0:any) => {
        return [p0_0,new i5.HttpInterceptorService()];
      },[i3.ɵh]),i0.ɵmpd(4608,i3.ɵd,i3.ɵd,([] as any[])),i0.ɵmpd(6144,i3.XhrFactory,
          (null as any),[i3.ɵd]),i0.ɵmpd(4608,i3.HttpXhrBackend,i3.HttpXhrBackend,
          [i3.XhrFactory]),i0.ɵmpd(6144,i3.HttpBackend,(null as any),[i3.HttpXhrBackend]),
          i0.ɵmpd(5120,i3.HttpHandler,i3.ɵinterceptingHandler,[i3.HttpBackend,[2,i3.HTTP_INTERCEPTORS]]),
          i0.ɵmpd(4608,i3.HttpClient,i3.HttpClient,[i3.HttpHandler]),i0.ɵmpd(4608,
              i4.NgLocalization,i4.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i6.FormBuilder,i6.FormBuilder,([] as any[])),i0.ɵmpd(4608,i6.ɵi,i6.ɵi,
              ([] as any[])),i0.ɵmpd(6144,i7.DIR_DOCUMENT,(null as any),[i8.DOCUMENT]),
          i0.ɵmpd(4608,i7.Directionality,i7.Directionality,[[2,i7.DIR_DOCUMENT]]),
          i0.ɵmpd(4608,i9.Platform,i9.Platform,([] as any[])),i0.ɵmpd(5120,i10.ScrollDispatcher,
              i10.SCROLL_DISPATCHER_PROVIDER_FACTORY,[[3,i10.ScrollDispatcher],i0.NgZone,
                  i9.Platform]),i0.ɵmpd(5120,i10.ViewportRuler,i10.VIEWPORT_RULER_PROVIDER_FACTORY,
              [[3,i10.ViewportRuler],i10.ScrollDispatcher]),i0.ɵmpd(4608,i11.ScrollStrategyOptions,
              i11.ScrollStrategyOptions,[i10.ScrollDispatcher,i10.ViewportRuler]),
          i0.ɵmpd(5120,i11.OverlayContainer,i11.ɵa,[[3,i11.OverlayContainer]]),i0.ɵmpd(4608,
              i11.ɵf,i11.ɵf,[i10.ViewportRuler]),i0.ɵmpd(4608,i11.Overlay,i11.Overlay,
              [i11.ScrollStrategyOptions,i11.OverlayContainer,i0.ComponentFactoryResolver,
                  i11.ɵf,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i11.ɵc,
              i11.ɵd,[i11.Overlay]),i0.ɵmpd(5120,i12.MD_AUTOCOMPLETE_SCROLL_STRATEGY,
              i12.MD_AUTOCOMPLETE_SCROLL_STRATEGY_PROVIDER_FACTORY,[i11.Overlay]),
          i0.ɵmpd(5120,i12.FocusOriginMonitor,i12.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,
              [[3,i12.FocusOriginMonitor],i0.NgZone,i9.Platform]),i0.ɵmpd(5120,i12.UniqueSelectionDispatcher,
              i12.ɵb,[[3,i12.UniqueSelectionDispatcher]]),i0.ɵmpd(4608,i13.MdMutationObserverFactory,
              i13.MdMutationObserverFactory,([] as any[])),i0.ɵmpd(4608,i14.InteractivityChecker,
              i14.InteractivityChecker,[i9.Platform]),i0.ɵmpd(4608,i14.FocusTrapFactory,
              i14.FocusTrapFactory,[i14.InteractivityChecker,i9.Platform,i0.NgZone]),
          i0.ɵmpd(5120,i14.LiveAnnouncer,i14.LIVE_ANNOUNCER_PROVIDER_FACTORY,[[3,i14.LiveAnnouncer],
              [2,i14.LIVE_ANNOUNCER_ELEMENT_TOKEN],i9.Platform]),i0.ɵmpd(5120,i12.MD_DIALOG_SCROLL_STRATEGY,
              i12.MD_DIALOG_SCROLL_STRATEGY_PROVIDER_FACTORY,[i11.Overlay]),i0.ɵmpd(4608,
              i12.MdDialog,i12.MdDialog,[i11.Overlay,i0.Injector,i12.MD_DIALOG_SCROLL_STRATEGY,
                  [2,i4.Location],[3,i12.MdDialog]]),i0.ɵmpd(5120,i12.MdIconRegistry,
              i12.ICON_REGISTRY_PROVIDER_FACTORY,[[3,i12.MdIconRegistry],[2,i15.Http],
                  i8.DomSanitizer]),i0.ɵmpd(4608,i12.MdDatepickerIntl,i12.MdDatepickerIntl,
              ([] as any[])),i0.ɵmpd(5120,i12.MD_DATEPICKER_SCROLL_STRATEGY,i12.MD_DATEPICKER_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i11.Overlay]),i0.ɵmpd(5120,i12.ɵl,i12.ɵm,[i11.Overlay]),i0.ɵmpd(5120,
              i12.MD_SELECT_SCROLL_STRATEGY,i12.MD_SELECT_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i11.Overlay]),i0.ɵmpd(5120,i12.MD_TOOLTIP_SCROLL_STRATEGY,i12.MD_TOOLTIP_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i11.Overlay]),i0.ɵmpd(4608,i12.MdPaginatorIntl,i12.MdPaginatorIntl,
              ([] as any[])),i0.ɵmpd(4608,i8.HAMMER_GESTURE_CONFIG,i12.GestureConfig,
              ([] as any[])),i0.ɵmpd(4608,i12.MdSnackBar,i12.MdSnackBar,[i11.Overlay,
              i14.LiveAnnouncer,i0.Injector,[3,i12.MdSnackBar]]),i0.ɵmpd(4608,i12.MdSortHeaderIntl,
              i12.MdSortHeaderIntl,([] as any[])),i0.ɵmpd(4608,i16.MatchMedia,i16.MatchMedia,
              [i0.NgZone]),i0.ɵmpd(4608,i17.BreakPointRegistry,i17.BreakPointRegistry,
              [i18.BREAKPOINTS]),i0.ɵmpd(4608,i19.MediaMonitor,i19.MediaMonitor,[i17.BreakPointRegistry,
              i16.MatchMedia]),i0.ɵmpd(4608,i20.ObservableMedia,i20.MediaService,[i16.MatchMedia,
              i17.BreakPointRegistry]),i0.ɵmpd(4608,i21.AuthService,i21.AuthService,
              [i3.HttpClient,i22.Router]),i0.ɵmpd(512,i3.HttpClientXsrfModule,i3.HttpClientXsrfModule,
              ([] as any[])),i0.ɵmpd(512,i3.HttpClientModule,i3.HttpClientModule,([] as any[])),
          i0.ɵmpd(512,i4.CommonModule,i4.CommonModule,([] as any[])),i0.ɵmpd(512,i6.ɵba,
              i6.ɵba,([] as any[])),i0.ɵmpd(512,i6.ReactiveFormsModule,i6.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(512,i12.CompatibilityModule,i12.CompatibilityModule,
              ([] as any[])),i0.ɵmpd(512,i7.BidiModule,i7.BidiModule,([] as any[])),
          i0.ɵmpd(256,i12.MATERIAL_SANITY_CHECKS,true,([] as any[])),i0.ɵmpd(512,i12.MdCommonModule,
              i12.MdCommonModule,[[2,i8.DOCUMENT],[2,i12.MATERIAL_SANITY_CHECKS]]),
          i0.ɵmpd(512,i9.PlatformModule,i9.PlatformModule,([] as any[])),i0.ɵmpd(512,
              i10.ScrollDispatchModule,i10.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,
              i12.MdRippleModule,i12.MdRippleModule,([] as any[])),i0.ɵmpd(512,i12.MdPseudoCheckboxModule,
              i12.MdPseudoCheckboxModule,([] as any[])),i0.ɵmpd(512,i12.MdOptionModule,
              i12.MdOptionModule,([] as any[])),i0.ɵmpd(512,i23.PortalModule,i23.PortalModule,
              ([] as any[])),i0.ɵmpd(512,i11.OverlayModule,i11.OverlayModule,([] as any[])),
          i0.ɵmpd(512,i12.MdAutocompleteModule,i12.MdAutocompleteModule,([] as any[])),
          i0.ɵmpd(512,i12.StyleModule,i12.StyleModule,([] as any[])),i0.ɵmpd(512,i12.MdButtonModule,
              i12.MdButtonModule,([] as any[])),i0.ɵmpd(512,i12.MdButtonToggleModule,
              i12.MdButtonToggleModule,([] as any[])),i0.ɵmpd(512,i12.MdCardModule,
              i12.MdCardModule,([] as any[])),i0.ɵmpd(512,i12.MdChipsModule,i12.MdChipsModule,
              ([] as any[])),i0.ɵmpd(512,i13.ObserversModule,i13.ObserversModule,([] as any[])),
          i0.ɵmpd(512,i12.MdCheckboxModule,i12.MdCheckboxModule,([] as any[])),i0.ɵmpd(512,
              i14.A11yModule,i14.A11yModule,([] as any[])),i0.ɵmpd(512,i12.MdDialogModule,
              i12.MdDialogModule,([] as any[])),i0.ɵmpd(512,i12.MdIconModule,i12.MdIconModule,
              ([] as any[])),i0.ɵmpd(512,i12.MdDatepickerModule,i12.MdDatepickerModule,
              ([] as any[])),i0.ɵmpd(512,i24.CdkTableModule,i24.CdkTableModule,([] as any[])),
          i0.ɵmpd(512,i12.MdTableModule,i12.MdTableModule,([] as any[])),i0.ɵmpd(512,
              i12.MdExpansionModule,i12.MdExpansionModule,([] as any[])),i0.ɵmpd(512,
              i12.MdFormFieldModule,i12.MdFormFieldModule,([] as any[])),i0.ɵmpd(512,
              i12.MdLineModule,i12.MdLineModule,([] as any[])),i0.ɵmpd(512,i12.MdGridListModule,
              i12.MdGridListModule,([] as any[])),i0.ɵmpd(512,i12.MdInputModule,i12.MdInputModule,
              ([] as any[])),i0.ɵmpd(512,i12.MdListModule,i12.MdListModule,([] as any[])),
          i0.ɵmpd(512,i12.MdMenuModule,i12.MdMenuModule,([] as any[])),i0.ɵmpd(512,
              i12.MdSelectModule,i12.MdSelectModule,([] as any[])),i0.ɵmpd(512,i12.MdTooltipModule,
              i12.MdTooltipModule,([] as any[])),i0.ɵmpd(512,i12.MdPaginatorModule,
              i12.MdPaginatorModule,([] as any[])),i0.ɵmpd(512,i12.MdProgressBarModule,
              i12.MdProgressBarModule,([] as any[])),i0.ɵmpd(512,i12.MdProgressSpinnerModule,
              i12.MdProgressSpinnerModule,([] as any[])),i0.ɵmpd(512,i12.MdRadioModule,
              i12.MdRadioModule,([] as any[])),i0.ɵmpd(512,i12.MdSidenavModule,i12.MdSidenavModule,
              ([] as any[])),i0.ɵmpd(512,i12.MdSliderModule,i12.MdSliderModule,([] as any[])),
          i0.ɵmpd(512,i12.MdSlideToggleModule,i12.MdSlideToggleModule,([] as any[])),
          i0.ɵmpd(512,i12.MdSnackBarModule,i12.MdSnackBarModule,([] as any[])),i0.ɵmpd(512,
              i12.MdSortModule,i12.MdSortModule,([] as any[])),i0.ɵmpd(512,i12.MdTabsModule,
              i12.MdTabsModule,([] as any[])),i0.ɵmpd(512,i12.MdToolbarModule,i12.MdToolbarModule,
              ([] as any[])),i0.ɵmpd(512,i12.MaterialModule,i12.MaterialModule,([] as any[])),
          i0.ɵmpd(512,i25.MediaQueriesModule,i25.MediaQueriesModule,([] as any[])),
          i0.ɵmpd(512,i26.FlexLayoutModule,i26.FlexLayoutModule,([] as any[])),i0.ɵmpd(512,
              i27.SharedModule,i27.SharedModule,([] as any[])),i0.ɵmpd(512,i1.CoreModule,
              i1.CoreModule,([] as any[])),i0.ɵmpd(256,i3.ɵe,'XSRF-TOKEN',([] as any[])),
          i0.ɵmpd(256,i3.ɵf,'X-XSRF-TOKEN',([] as any[])),i0.ɵmpd(256,i12.MD_MENU_DEFAULT_OPTIONS,
              {overlapTrigger:true,xPosition:'after',yPosition:'below'},([] as any[])),
          i0.ɵmpd(256,i18.BREAKPOINTS,i18.RAW_DEFAULTS,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWxleC9Db2RlL0phdmFTY3JpcHQvdHh0ci5pby9zcmMvYXBwL2NvcmUvY29yZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvQWxleC9Db2RlL0phdmFTY3JpcHQvdHh0ci5pby9zcmMvYXBwL2NvcmUvY29yZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
