/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/core/core.module';
import * as i2 from '../../../node_modules/@angular/material/typings/index.ngfactory';
import * as i3 from '@angular/common/http';
import * as i4 from '@angular/common';
import * as i5 from '../../../../src/app/core/services/session-storage.service';
import * as i6 from '../../../../src/app/core/http.interceptors';
import * as i7 from '@angular/forms';
import * as i8 from '@angular/cdk/bidi';
import * as i9 from '@angular/platform-browser';
import * as i10 from '@angular/cdk/platform';
import * as i11 from '@angular/cdk/scrolling';
import * as i12 from '@angular/cdk/overlay';
import * as i13 from '@angular/material';
import * as i14 from '@angular/cdk/observers';
import * as i15 from '@angular/cdk/a11y';
import * as i16 from '@angular/http';
import * as i17 from '@angular/flex-layout/media-query/match-media';
import * as i18 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as i19 from '@angular/flex-layout/media-query/breakpoints/break-points';
import * as i20 from '@angular/flex-layout/media-query/media-monitor';
import * as i21 from '@angular/flex-layout/media-query/observable-media-service';
import * as i22 from '../../../../src/app/core/services/auth.service';
import * as i23 from '@angular/router';
import * as i24 from '@angular/cdk/portal';
import * as i25 from '@angular/cdk/table';
import * as i26 from '@angular/flex-layout/media-query/_module';
import * as i27 from '@angular/flex-layout/flexbox/_module';
import * as i28 from '../../../../src/app/core/shared.module';
export const CoreModuleNgFactory:i0.NgModuleFactory<i1.CoreModule> = i0.ɵcmf(i1.CoreModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.MdDialogContainerNgFactory,i2.MdDatepickerContentNgFactory,i2.TooltipComponentNgFactory,
              i2.MdSnackBarContainerNgFactory,i2.SimpleSnackBarNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i3.HttpXsrfTokenExtractor,i3.ɵg,[i4.DOCUMENT,
          i0.PLATFORM_ID,i3.ɵe]),i0.ɵmpd(4608,i3.ɵh,i3.ɵh,[i3.HttpXsrfTokenExtractor,
          i3.ɵf]),i0.ɵmpd(4608,i5.SessionStorageService,i5.SessionStorageService,([] as any[])),
          i0.ɵmpd(5120,i3.HTTP_INTERCEPTORS,(p0_0:any,p1_0:any) => {
            return [p0_0,new i6.HttpInterceptorService(p1_0)];
          },[i3.ɵh,i5.SessionStorageService]),i0.ɵmpd(4608,i3.ɵd,i3.ɵd,([] as any[])),
          i0.ɵmpd(6144,i3.XhrFactory,(null as any),[i3.ɵd]),i0.ɵmpd(4608,i3.HttpXhrBackend,
              i3.HttpXhrBackend,[i3.XhrFactory]),i0.ɵmpd(6144,i3.HttpBackend,(null as any),
              [i3.HttpXhrBackend]),i0.ɵmpd(5120,i3.HttpHandler,i3.ɵinterceptingHandler,
              [i3.HttpBackend,[2,i3.HTTP_INTERCEPTORS]]),i0.ɵmpd(4608,i3.HttpClient,
              i3.HttpClient,[i3.HttpHandler]),i0.ɵmpd(4608,i4.NgLocalization,i4.NgLocaleLocalization,
              [i0.LOCALE_ID]),i0.ɵmpd(4608,i7.FormBuilder,i7.FormBuilder,([] as any[])),
          i0.ɵmpd(4608,i7.ɵi,i7.ɵi,([] as any[])),i0.ɵmpd(6144,i8.DIR_DOCUMENT,(null as any),
              [i9.DOCUMENT]),i0.ɵmpd(4608,i8.Directionality,i8.Directionality,[[2,
              i8.DIR_DOCUMENT]]),i0.ɵmpd(4608,i10.Platform,i10.Platform,([] as any[])),
          i0.ɵmpd(5120,i11.ScrollDispatcher,i11.SCROLL_DISPATCHER_PROVIDER_FACTORY,
              [[3,i11.ScrollDispatcher],i0.NgZone,i10.Platform]),i0.ɵmpd(5120,i11.ViewportRuler,
              i11.VIEWPORT_RULER_PROVIDER_FACTORY,[[3,i11.ViewportRuler],i11.ScrollDispatcher]),
          i0.ɵmpd(4608,i12.ScrollStrategyOptions,i12.ScrollStrategyOptions,[i11.ScrollDispatcher,
              i11.ViewportRuler]),i0.ɵmpd(5120,i12.OverlayContainer,i12.ɵa,[[3,i12.OverlayContainer]]),
          i0.ɵmpd(4608,i12.ɵf,i12.ɵf,[i11.ViewportRuler]),i0.ɵmpd(4608,i12.Overlay,
              i12.Overlay,[i12.ScrollStrategyOptions,i12.OverlayContainer,i0.ComponentFactoryResolver,
                  i12.ɵf,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i12.ɵc,
              i12.ɵd,[i12.Overlay]),i0.ɵmpd(5120,i13.MD_AUTOCOMPLETE_SCROLL_STRATEGY,
              i13.MD_AUTOCOMPLETE_SCROLL_STRATEGY_PROVIDER_FACTORY,[i12.Overlay]),
          i0.ɵmpd(5120,i13.FocusOriginMonitor,i13.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,
              [[3,i13.FocusOriginMonitor],i0.NgZone,i10.Platform]),i0.ɵmpd(5120,i13.UniqueSelectionDispatcher,
              i13.ɵb,[[3,i13.UniqueSelectionDispatcher]]),i0.ɵmpd(4608,i14.MdMutationObserverFactory,
              i14.MdMutationObserverFactory,([] as any[])),i0.ɵmpd(4608,i15.InteractivityChecker,
              i15.InteractivityChecker,[i10.Platform]),i0.ɵmpd(4608,i15.FocusTrapFactory,
              i15.FocusTrapFactory,[i15.InteractivityChecker,i10.Platform,i0.NgZone]),
          i0.ɵmpd(5120,i15.LiveAnnouncer,i15.LIVE_ANNOUNCER_PROVIDER_FACTORY,[[3,i15.LiveAnnouncer],
              [2,i15.LIVE_ANNOUNCER_ELEMENT_TOKEN],i10.Platform]),i0.ɵmpd(5120,i13.MD_DIALOG_SCROLL_STRATEGY,
              i13.MD_DIALOG_SCROLL_STRATEGY_PROVIDER_FACTORY,[i12.Overlay]),i0.ɵmpd(4608,
              i13.MdDialog,i13.MdDialog,[i12.Overlay,i0.Injector,i13.MD_DIALOG_SCROLL_STRATEGY,
                  [2,i4.Location],[3,i13.MdDialog]]),i0.ɵmpd(5120,i13.MdIconRegistry,
              i13.ICON_REGISTRY_PROVIDER_FACTORY,[[3,i13.MdIconRegistry],[2,i16.Http],
                  i9.DomSanitizer]),i0.ɵmpd(4608,i13.MdDatepickerIntl,i13.MdDatepickerIntl,
              ([] as any[])),i0.ɵmpd(5120,i13.MD_DATEPICKER_SCROLL_STRATEGY,i13.MD_DATEPICKER_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i12.Overlay]),i0.ɵmpd(5120,i13.ɵl,i13.ɵm,[i12.Overlay]),i0.ɵmpd(5120,
              i13.MD_SELECT_SCROLL_STRATEGY,i13.MD_SELECT_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i12.Overlay]),i0.ɵmpd(5120,i13.MD_TOOLTIP_SCROLL_STRATEGY,i13.MD_TOOLTIP_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i12.Overlay]),i0.ɵmpd(4608,i13.MdPaginatorIntl,i13.MdPaginatorIntl,
              ([] as any[])),i0.ɵmpd(4608,i9.HAMMER_GESTURE_CONFIG,i13.GestureConfig,
              ([] as any[])),i0.ɵmpd(4608,i13.MdSnackBar,i13.MdSnackBar,[i12.Overlay,
              i15.LiveAnnouncer,i0.Injector,[3,i13.MdSnackBar]]),i0.ɵmpd(4608,i13.MdSortHeaderIntl,
              i13.MdSortHeaderIntl,([] as any[])),i0.ɵmpd(4608,i17.MatchMedia,i17.MatchMedia,
              [i0.NgZone]),i0.ɵmpd(4608,i18.BreakPointRegistry,i18.BreakPointRegistry,
              [i19.BREAKPOINTS]),i0.ɵmpd(4608,i20.MediaMonitor,i20.MediaMonitor,[i18.BreakPointRegistry,
              i17.MatchMedia]),i0.ɵmpd(4608,i21.ObservableMedia,i21.MediaService,[i17.MatchMedia,
              i18.BreakPointRegistry]),i0.ɵmpd(4608,i22.AuthService,i22.AuthService,
              [i3.HttpClient,i5.SessionStorageService,i23.Router]),i0.ɵmpd(512,i3.HttpClientXsrfModule,
              i3.HttpClientXsrfModule,([] as any[])),i0.ɵmpd(512,i3.HttpClientModule,
              i3.HttpClientModule,([] as any[])),i0.ɵmpd(512,i4.CommonModule,i4.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i7.ɵba,i7.ɵba,([] as any[])),i0.ɵmpd(512,
              i7.ReactiveFormsModule,i7.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,
              i13.CompatibilityModule,i13.CompatibilityModule,([] as any[])),i0.ɵmpd(512,
              i8.BidiModule,i8.BidiModule,([] as any[])),i0.ɵmpd(256,i13.MATERIAL_SANITY_CHECKS,
              true,([] as any[])),i0.ɵmpd(512,i13.MdCommonModule,i13.MdCommonModule,
              [[2,i9.DOCUMENT],[2,i13.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i10.PlatformModule,
              i10.PlatformModule,([] as any[])),i0.ɵmpd(512,i11.ScrollDispatchModule,
              i11.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,i13.MdRippleModule,
              i13.MdRippleModule,([] as any[])),i0.ɵmpd(512,i13.MdPseudoCheckboxModule,
              i13.MdPseudoCheckboxModule,([] as any[])),i0.ɵmpd(512,i13.MdOptionModule,
              i13.MdOptionModule,([] as any[])),i0.ɵmpd(512,i24.PortalModule,i24.PortalModule,
              ([] as any[])),i0.ɵmpd(512,i12.OverlayModule,i12.OverlayModule,([] as any[])),
          i0.ɵmpd(512,i13.MdAutocompleteModule,i13.MdAutocompleteModule,([] as any[])),
          i0.ɵmpd(512,i13.StyleModule,i13.StyleModule,([] as any[])),i0.ɵmpd(512,i13.MdButtonModule,
              i13.MdButtonModule,([] as any[])),i0.ɵmpd(512,i13.MdButtonToggleModule,
              i13.MdButtonToggleModule,([] as any[])),i0.ɵmpd(512,i13.MdCardModule,
              i13.MdCardModule,([] as any[])),i0.ɵmpd(512,i13.MdChipsModule,i13.MdChipsModule,
              ([] as any[])),i0.ɵmpd(512,i14.ObserversModule,i14.ObserversModule,([] as any[])),
          i0.ɵmpd(512,i13.MdCheckboxModule,i13.MdCheckboxModule,([] as any[])),i0.ɵmpd(512,
              i15.A11yModule,i15.A11yModule,([] as any[])),i0.ɵmpd(512,i13.MdDialogModule,
              i13.MdDialogModule,([] as any[])),i0.ɵmpd(512,i13.MdIconModule,i13.MdIconModule,
              ([] as any[])),i0.ɵmpd(512,i13.MdDatepickerModule,i13.MdDatepickerModule,
              ([] as any[])),i0.ɵmpd(512,i25.CdkTableModule,i25.CdkTableModule,([] as any[])),
          i0.ɵmpd(512,i13.MdTableModule,i13.MdTableModule,([] as any[])),i0.ɵmpd(512,
              i13.MdExpansionModule,i13.MdExpansionModule,([] as any[])),i0.ɵmpd(512,
              i13.MdFormFieldModule,i13.MdFormFieldModule,([] as any[])),i0.ɵmpd(512,
              i13.MdLineModule,i13.MdLineModule,([] as any[])),i0.ɵmpd(512,i13.MdGridListModule,
              i13.MdGridListModule,([] as any[])),i0.ɵmpd(512,i13.MdInputModule,i13.MdInputModule,
              ([] as any[])),i0.ɵmpd(512,i13.MdListModule,i13.MdListModule,([] as any[])),
          i0.ɵmpd(512,i13.MdMenuModule,i13.MdMenuModule,([] as any[])),i0.ɵmpd(512,
              i13.MdSelectModule,i13.MdSelectModule,([] as any[])),i0.ɵmpd(512,i13.MdTooltipModule,
              i13.MdTooltipModule,([] as any[])),i0.ɵmpd(512,i13.MdPaginatorModule,
              i13.MdPaginatorModule,([] as any[])),i0.ɵmpd(512,i13.MdProgressBarModule,
              i13.MdProgressBarModule,([] as any[])),i0.ɵmpd(512,i13.MdProgressSpinnerModule,
              i13.MdProgressSpinnerModule,([] as any[])),i0.ɵmpd(512,i13.MdRadioModule,
              i13.MdRadioModule,([] as any[])),i0.ɵmpd(512,i13.MdSidenavModule,i13.MdSidenavModule,
              ([] as any[])),i0.ɵmpd(512,i13.MdSliderModule,i13.MdSliderModule,([] as any[])),
          i0.ɵmpd(512,i13.MdSlideToggleModule,i13.MdSlideToggleModule,([] as any[])),
          i0.ɵmpd(512,i13.MdSnackBarModule,i13.MdSnackBarModule,([] as any[])),i0.ɵmpd(512,
              i13.MdSortModule,i13.MdSortModule,([] as any[])),i0.ɵmpd(512,i13.MdTabsModule,
              i13.MdTabsModule,([] as any[])),i0.ɵmpd(512,i13.MdToolbarModule,i13.MdToolbarModule,
              ([] as any[])),i0.ɵmpd(512,i13.MaterialModule,i13.MaterialModule,([] as any[])),
          i0.ɵmpd(512,i26.MediaQueriesModule,i26.MediaQueriesModule,([] as any[])),
          i0.ɵmpd(512,i27.FlexLayoutModule,i27.FlexLayoutModule,([] as any[])),i0.ɵmpd(512,
              i28.SharedModule,i28.SharedModule,([] as any[])),i0.ɵmpd(512,i1.CoreModule,
              i1.CoreModule,([] as any[])),i0.ɵmpd(256,i3.ɵe,'XSRF-TOKEN',([] as any[])),
          i0.ɵmpd(256,i3.ɵf,'X-XSRF-TOKEN',([] as any[])),i0.ɵmpd(256,i13.MD_MENU_DEFAULT_OPTIONS,
              {overlapTrigger:true,xPosition:'after',yPosition:'below'},([] as any[])),
          i0.ɵmpd(256,i19.BREAKPOINTS,i19.RAW_DEFAULTS,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWxleC9Db2RlL3R4dHIuaW8vc3JjL2FwcC9jb3JlL2NvcmUubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FsZXgvQ29kZS90eHRyLmlvL3NyYy9hcHAvY29yZS9jb3JlLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
