/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/core/shared.module';
import * as i2 from '../../../node_modules/@angular/material/typings/index.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/forms';
import * as i5 from '@angular/cdk/bidi';
import * as i6 from '@angular/platform-browser';
import * as i7 from '@angular/cdk/platform';
import * as i8 from '@angular/cdk/scrolling';
import * as i9 from '@angular/cdk/overlay';
import * as i10 from '@angular/material';
import * as i11 from '@angular/cdk/observers';
import * as i12 from '@angular/cdk/a11y';
import * as i13 from '@angular/http';
import * as i14 from '@angular/flex-layout/media-query/match-media';
import * as i15 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as i16 from '@angular/flex-layout/media-query/breakpoints/break-points';
import * as i17 from '@angular/flex-layout/media-query/media-monitor';
import * as i18 from '@angular/flex-layout/media-query/observable-media-service';
import * as i19 from '@angular/cdk/portal';
import * as i20 from '@angular/cdk/table';
import * as i21 from '@angular/flex-layout/media-query/_module';
import * as i22 from '@angular/flex-layout/flexbox/_module';
export const SharedModuleNgFactory:i0.NgModuleFactory<i1.SharedModule> = i0.ɵcmf(i1.SharedModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.MdDialogContainerNgFactory,i2.MdDatepickerContentNgFactory,i2.TooltipComponentNgFactory,
              i2.MdSnackBarContainerNgFactory,i2.SimpleSnackBarNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i4.FormBuilder,i4.FormBuilder,([] as any[])),
          i0.ɵmpd(4608,i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(6144,i5.DIR_DOCUMENT,(null as any),
              [i6.DOCUMENT]),i0.ɵmpd(4608,i5.Directionality,i5.Directionality,[[2,
              i5.DIR_DOCUMENT]]),i0.ɵmpd(4608,i7.Platform,i7.Platform,([] as any[])),
          i0.ɵmpd(5120,i8.ScrollDispatcher,i8.SCROLL_DISPATCHER_PROVIDER_FACTORY,[[3,
              i8.ScrollDispatcher],i0.NgZone,i7.Platform]),i0.ɵmpd(5120,i8.ViewportRuler,
              i8.VIEWPORT_RULER_PROVIDER_FACTORY,[[3,i8.ViewportRuler],i8.ScrollDispatcher]),
          i0.ɵmpd(4608,i9.ScrollStrategyOptions,i9.ScrollStrategyOptions,[i8.ScrollDispatcher,
              i8.ViewportRuler]),i0.ɵmpd(5120,i9.OverlayContainer,i9.ɵa,[[3,i9.OverlayContainer]]),
          i0.ɵmpd(4608,i9.ɵf,i9.ɵf,[i8.ViewportRuler]),i0.ɵmpd(4608,i9.Overlay,i9.Overlay,
              [i9.ScrollStrategyOptions,i9.OverlayContainer,i0.ComponentFactoryResolver,
                  i9.ɵf,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i9.ɵc,
              i9.ɵd,[i9.Overlay]),i0.ɵmpd(5120,i10.MD_AUTOCOMPLETE_SCROLL_STRATEGY,
              i10.MD_AUTOCOMPLETE_SCROLL_STRATEGY_PROVIDER_FACTORY,[i9.Overlay]),i0.ɵmpd(5120,
              i10.FocusOriginMonitor,i10.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,[[3,
                  i10.FocusOriginMonitor],i0.NgZone,i7.Platform]),i0.ɵmpd(5120,i10.UniqueSelectionDispatcher,
              i10.ɵb,[[3,i10.UniqueSelectionDispatcher]]),i0.ɵmpd(4608,i11.MdMutationObserverFactory,
              i11.MdMutationObserverFactory,([] as any[])),i0.ɵmpd(4608,i12.InteractivityChecker,
              i12.InteractivityChecker,[i7.Platform]),i0.ɵmpd(4608,i12.FocusTrapFactory,
              i12.FocusTrapFactory,[i12.InteractivityChecker,i7.Platform,i0.NgZone]),
          i0.ɵmpd(5120,i12.LiveAnnouncer,i12.LIVE_ANNOUNCER_PROVIDER_FACTORY,[[3,i12.LiveAnnouncer],
              [2,i12.LIVE_ANNOUNCER_ELEMENT_TOKEN],i7.Platform]),i0.ɵmpd(5120,i10.MD_DIALOG_SCROLL_STRATEGY,
              i10.MD_DIALOG_SCROLL_STRATEGY_PROVIDER_FACTORY,[i9.Overlay]),i0.ɵmpd(4608,
              i10.MdDialog,i10.MdDialog,[i9.Overlay,i0.Injector,i10.MD_DIALOG_SCROLL_STRATEGY,
                  [2,i3.Location],[3,i10.MdDialog]]),i0.ɵmpd(5120,i10.MdIconRegistry,
              i10.ICON_REGISTRY_PROVIDER_FACTORY,[[3,i10.MdIconRegistry],[2,i13.Http],
                  i6.DomSanitizer]),i0.ɵmpd(4608,i10.MdDatepickerIntl,i10.MdDatepickerIntl,
              ([] as any[])),i0.ɵmpd(5120,i10.MD_DATEPICKER_SCROLL_STRATEGY,i10.MD_DATEPICKER_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i9.Overlay]),i0.ɵmpd(5120,i10.ɵl,i10.ɵm,[i9.Overlay]),i0.ɵmpd(5120,
              i10.MD_SELECT_SCROLL_STRATEGY,i10.MD_SELECT_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i9.Overlay]),i0.ɵmpd(5120,i10.MD_TOOLTIP_SCROLL_STRATEGY,i10.MD_TOOLTIP_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i9.Overlay]),i0.ɵmpd(4608,i10.MdPaginatorIntl,i10.MdPaginatorIntl,([] as any[])),
          i0.ɵmpd(4608,i6.HAMMER_GESTURE_CONFIG,i10.GestureConfig,([] as any[])),i0.ɵmpd(4608,
              i10.MdSnackBar,i10.MdSnackBar,[i9.Overlay,i12.LiveAnnouncer,i0.Injector,
                  [3,i10.MdSnackBar]]),i0.ɵmpd(4608,i10.MdSortHeaderIntl,i10.MdSortHeaderIntl,
              ([] as any[])),i0.ɵmpd(4608,i14.MatchMedia,i14.MatchMedia,[i0.NgZone]),
          i0.ɵmpd(4608,i15.BreakPointRegistry,i15.BreakPointRegistry,[i16.BREAKPOINTS]),
          i0.ɵmpd(4608,i17.MediaMonitor,i17.MediaMonitor,[i15.BreakPointRegistry,i14.MatchMedia]),
          i0.ɵmpd(4608,i18.ObservableMedia,i18.MediaService,[i14.MatchMedia,i15.BreakPointRegistry]),
          i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,([] as any[])),i0.ɵmpd(512,i4.ɵba,
              i4.ɵba,([] as any[])),i0.ɵmpd(512,i4.ReactiveFormsModule,i4.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(512,i10.CompatibilityModule,i10.CompatibilityModule,
              ([] as any[])),i0.ɵmpd(512,i5.BidiModule,i5.BidiModule,([] as any[])),
          i0.ɵmpd(256,i10.MATERIAL_SANITY_CHECKS,true,([] as any[])),i0.ɵmpd(512,i10.MdCommonModule,
              i10.MdCommonModule,[[2,i6.DOCUMENT],[2,i10.MATERIAL_SANITY_CHECKS]]),
          i0.ɵmpd(512,i7.PlatformModule,i7.PlatformModule,([] as any[])),i0.ɵmpd(512,
              i8.ScrollDispatchModule,i8.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,
              i10.MdRippleModule,i10.MdRippleModule,([] as any[])),i0.ɵmpd(512,i10.MdPseudoCheckboxModule,
              i10.MdPseudoCheckboxModule,([] as any[])),i0.ɵmpd(512,i10.MdOptionModule,
              i10.MdOptionModule,([] as any[])),i0.ɵmpd(512,i19.PortalModule,i19.PortalModule,
              ([] as any[])),i0.ɵmpd(512,i9.OverlayModule,i9.OverlayModule,([] as any[])),
          i0.ɵmpd(512,i10.MdAutocompleteModule,i10.MdAutocompleteModule,([] as any[])),
          i0.ɵmpd(512,i10.StyleModule,i10.StyleModule,([] as any[])),i0.ɵmpd(512,i10.MdButtonModule,
              i10.MdButtonModule,([] as any[])),i0.ɵmpd(512,i10.MdButtonToggleModule,
              i10.MdButtonToggleModule,([] as any[])),i0.ɵmpd(512,i10.MdCardModule,
              i10.MdCardModule,([] as any[])),i0.ɵmpd(512,i10.MdChipsModule,i10.MdChipsModule,
              ([] as any[])),i0.ɵmpd(512,i11.ObserversModule,i11.ObserversModule,([] as any[])),
          i0.ɵmpd(512,i10.MdCheckboxModule,i10.MdCheckboxModule,([] as any[])),i0.ɵmpd(512,
              i12.A11yModule,i12.A11yModule,([] as any[])),i0.ɵmpd(512,i10.MdDialogModule,
              i10.MdDialogModule,([] as any[])),i0.ɵmpd(512,i10.MdIconModule,i10.MdIconModule,
              ([] as any[])),i0.ɵmpd(512,i10.MdDatepickerModule,i10.MdDatepickerModule,
              ([] as any[])),i0.ɵmpd(512,i20.CdkTableModule,i20.CdkTableModule,([] as any[])),
          i0.ɵmpd(512,i10.MdTableModule,i10.MdTableModule,([] as any[])),i0.ɵmpd(512,
              i10.MdExpansionModule,i10.MdExpansionModule,([] as any[])),i0.ɵmpd(512,
              i10.MdFormFieldModule,i10.MdFormFieldModule,([] as any[])),i0.ɵmpd(512,
              i10.MdLineModule,i10.MdLineModule,([] as any[])),i0.ɵmpd(512,i10.MdGridListModule,
              i10.MdGridListModule,([] as any[])),i0.ɵmpd(512,i10.MdInputModule,i10.MdInputModule,
              ([] as any[])),i0.ɵmpd(512,i10.MdListModule,i10.MdListModule,([] as any[])),
          i0.ɵmpd(512,i10.MdMenuModule,i10.MdMenuModule,([] as any[])),i0.ɵmpd(512,
              i10.MdSelectModule,i10.MdSelectModule,([] as any[])),i0.ɵmpd(512,i10.MdTooltipModule,
              i10.MdTooltipModule,([] as any[])),i0.ɵmpd(512,i10.MdPaginatorModule,
              i10.MdPaginatorModule,([] as any[])),i0.ɵmpd(512,i10.MdProgressBarModule,
              i10.MdProgressBarModule,([] as any[])),i0.ɵmpd(512,i10.MdProgressSpinnerModule,
              i10.MdProgressSpinnerModule,([] as any[])),i0.ɵmpd(512,i10.MdRadioModule,
              i10.MdRadioModule,([] as any[])),i0.ɵmpd(512,i10.MdSidenavModule,i10.MdSidenavModule,
              ([] as any[])),i0.ɵmpd(512,i10.MdSliderModule,i10.MdSliderModule,([] as any[])),
          i0.ɵmpd(512,i10.MdSlideToggleModule,i10.MdSlideToggleModule,([] as any[])),
          i0.ɵmpd(512,i10.MdSnackBarModule,i10.MdSnackBarModule,([] as any[])),i0.ɵmpd(512,
              i10.MdSortModule,i10.MdSortModule,([] as any[])),i0.ɵmpd(512,i10.MdTabsModule,
              i10.MdTabsModule,([] as any[])),i0.ɵmpd(512,i10.MdToolbarModule,i10.MdToolbarModule,
              ([] as any[])),i0.ɵmpd(512,i10.MaterialModule,i10.MaterialModule,([] as any[])),
          i0.ɵmpd(512,i21.MediaQueriesModule,i21.MediaQueriesModule,([] as any[])),
          i0.ɵmpd(512,i22.FlexLayoutModule,i22.FlexLayoutModule,([] as any[])),i0.ɵmpd(512,
              i1.SharedModule,i1.SharedModule,([] as any[])),i0.ɵmpd(256,i10.MD_MENU_DEFAULT_OPTIONS,
              {overlapTrigger:true,xPosition:'after',yPosition:'below'},([] as any[])),
          i0.ɵmpd(256,i16.BREAKPOINTS,i16.RAW_DEFAULTS,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWxleC9Db2RlL3R4dHIuaW8vc3JjL2FwcC9jb3JlL3NoYXJlZC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvQWxleC9Db2RlL3R4dHIuaW8vc3JjL2FwcC9jb3JlL3NoYXJlZC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
