/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../src/app/core/login/login-routing.module';
import * as i2 from './login.component.ngfactory';
import * as i3 from '@angular/router';
import * as i4 from '../../../../../src/app/core/login/login.component';
export const LoginRoutingModuleNgFactory:i0.NgModuleFactory<i1.LoginRoutingModule> = i0.ɵcmf(i1.LoginRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.LoginComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(512,i3.RouterModule,i3.RouterModule,[[2,i3.ɵa],[2,i3.Router]]),i0.ɵmpd(512,
              i1.LoginRoutingModule,i1.LoginRoutingModule,([] as any[])),i0.ɵmpd(1024,
              i3.ROUTES,() => {
                return [[{path:'login',component:i4.LoginComponent}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWxleC9Db2RlL3R4dHIuaW8vc3JjL2FwcC9jb3JlL2xvZ2luL2xvZ2luLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FsZXgvQ29kZS90eHRyLmlvL3NyYy9hcHAvY29yZS9sb2dpbi9sb2dpbi1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
