/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['[_nghost-%COMP%] {\r\n  float: center;\r\n  margin: auto;\r\n  background: darkgrey;\r\n  padding: 10px;\r\n  width: 400px;\r\n  height: 400px;\r\n  border-radius: 10px;\r\n  border: 3px solid #478cff;\r\n  margin-top: 100px;\r\n}\r\n.actions[_ngcontent-%COMP%] {\r\n  width: 100%;\r\n}\r\n\r\nmd-divider[_ngcontent-%COMP%] {\r\n  border-width: 0.5px;\r\n  border-style: solid;\r\n  border-color: grey;\r\n}\r\n.email[_ngcontent-%COMP%] {\r\n  padding-top: 10px;\r\n}'];
//# sourceMappingURL=login.component.scss.shim.ngstyle.js.map