/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../src/app/core/login/login.module';
import * as i2 from '../../../../node_modules/@angular/material/typings/index.ngfactory';
import * as i3 from './login.component.ngfactory';
import * as i4 from '@angular/common';
import * as i5 from '@angular/forms';
import * as i6 from '@angular/cdk/bidi';
import * as i7 from '@angular/platform-browser';
import * as i8 from '@angular/cdk/platform';
import * as i9 from '@angular/cdk/scrolling';
import * as i10 from '@angular/cdk/overlay';
import * as i11 from '@angular/material';
import * as i12 from '@angular/cdk/observers';
import * as i13 from '@angular/cdk/a11y';
import * as i14 from '@angular/http';
import * as i15 from '@angular/flex-layout/media-query/match-media';
import * as i16 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as i17 from '@angular/flex-layout/media-query/breakpoints/break-points';
import * as i18 from '@angular/flex-layout/media-query/media-monitor';
import * as i19 from '@angular/flex-layout/media-query/observable-media-service';
import * as i20 from '@angular/cdk/portal';
import * as i21 from '@angular/cdk/table';
import * as i22 from '@angular/flex-layout/media-query/_module';
import * as i23 from '@angular/flex-layout/flexbox/_module';
import * as i24 from '../../../../../src/app/core/shared.module';
import * as i25 from '@angular/router';
import * as i26 from '../../../../../src/app/core/login/login-routing.module';
import * as i27 from '../../../../../src/app/core/login/login.component';
export const LoginModuleNgFactory:i0.NgModuleFactory<i1.LoginModule> = i0.ɵcmf(i1.LoginModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.MdDialogContainerNgFactory,i2.MdDatepickerContentNgFactory,i2.TooltipComponentNgFactory,
              i2.MdSnackBarContainerNgFactory,i2.SimpleSnackBarNgFactory,i3.LoginComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i4.NgLocalization,
          i4.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i5.FormBuilder,i5.FormBuilder,
          ([] as any[])),i0.ɵmpd(4608,i5.ɵi,i5.ɵi,([] as any[])),i0.ɵmpd(6144,i6.DIR_DOCUMENT,
          (null as any),[i7.DOCUMENT]),i0.ɵmpd(4608,i6.Directionality,i6.Directionality,
          [[2,i6.DIR_DOCUMENT]]),i0.ɵmpd(4608,i8.Platform,i8.Platform,([] as any[])),
          i0.ɵmpd(5120,i9.ScrollDispatcher,i9.SCROLL_DISPATCHER_PROVIDER_FACTORY,[[3,
              i9.ScrollDispatcher],i0.NgZone,i8.Platform]),i0.ɵmpd(5120,i9.ViewportRuler,
              i9.VIEWPORT_RULER_PROVIDER_FACTORY,[[3,i9.ViewportRuler],i9.ScrollDispatcher]),
          i0.ɵmpd(4608,i10.ScrollStrategyOptions,i10.ScrollStrategyOptions,[i9.ScrollDispatcher,
              i9.ViewportRuler]),i0.ɵmpd(5120,i10.OverlayContainer,i10.ɵa,[[3,i10.OverlayContainer]]),
          i0.ɵmpd(4608,i10.ɵf,i10.ɵf,[i9.ViewportRuler]),i0.ɵmpd(4608,i10.Overlay,
              i10.Overlay,[i10.ScrollStrategyOptions,i10.OverlayContainer,i0.ComponentFactoryResolver,
                  i10.ɵf,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i10.ɵc,
              i10.ɵd,[i10.Overlay]),i0.ɵmpd(5120,i11.MD_AUTOCOMPLETE_SCROLL_STRATEGY,
              i11.MD_AUTOCOMPLETE_SCROLL_STRATEGY_PROVIDER_FACTORY,[i10.Overlay]),
          i0.ɵmpd(5120,i11.FocusOriginMonitor,i11.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,
              [[3,i11.FocusOriginMonitor],i0.NgZone,i8.Platform]),i0.ɵmpd(5120,i11.UniqueSelectionDispatcher,
              i11.ɵb,[[3,i11.UniqueSelectionDispatcher]]),i0.ɵmpd(4608,i12.MdMutationObserverFactory,
              i12.MdMutationObserverFactory,([] as any[])),i0.ɵmpd(4608,i13.InteractivityChecker,
              i13.InteractivityChecker,[i8.Platform]),i0.ɵmpd(4608,i13.FocusTrapFactory,
              i13.FocusTrapFactory,[i13.InteractivityChecker,i8.Platform,i0.NgZone]),
          i0.ɵmpd(5120,i13.LiveAnnouncer,i13.LIVE_ANNOUNCER_PROVIDER_FACTORY,[[3,i13.LiveAnnouncer],
              [2,i13.LIVE_ANNOUNCER_ELEMENT_TOKEN],i8.Platform]),i0.ɵmpd(5120,i11.MD_DIALOG_SCROLL_STRATEGY,
              i11.MD_DIALOG_SCROLL_STRATEGY_PROVIDER_FACTORY,[i10.Overlay]),i0.ɵmpd(4608,
              i11.MdDialog,i11.MdDialog,[i10.Overlay,i0.Injector,i11.MD_DIALOG_SCROLL_STRATEGY,
                  [2,i4.Location],[3,i11.MdDialog]]),i0.ɵmpd(5120,i11.MdIconRegistry,
              i11.ICON_REGISTRY_PROVIDER_FACTORY,[[3,i11.MdIconRegistry],[2,i14.Http],
                  i7.DomSanitizer]),i0.ɵmpd(4608,i11.MdDatepickerIntl,i11.MdDatepickerIntl,
              ([] as any[])),i0.ɵmpd(5120,i11.MD_DATEPICKER_SCROLL_STRATEGY,i11.MD_DATEPICKER_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i10.Overlay]),i0.ɵmpd(5120,i11.ɵl,i11.ɵm,[i10.Overlay]),i0.ɵmpd(5120,
              i11.MD_SELECT_SCROLL_STRATEGY,i11.MD_SELECT_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i10.Overlay]),i0.ɵmpd(5120,i11.MD_TOOLTIP_SCROLL_STRATEGY,i11.MD_TOOLTIP_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i10.Overlay]),i0.ɵmpd(4608,i11.MdPaginatorIntl,i11.MdPaginatorIntl,
              ([] as any[])),i0.ɵmpd(4608,i7.HAMMER_GESTURE_CONFIG,i11.GestureConfig,
              ([] as any[])),i0.ɵmpd(4608,i11.MdSnackBar,i11.MdSnackBar,[i10.Overlay,
              i13.LiveAnnouncer,i0.Injector,[3,i11.MdSnackBar]]),i0.ɵmpd(4608,i11.MdSortHeaderIntl,
              i11.MdSortHeaderIntl,([] as any[])),i0.ɵmpd(4608,i15.MatchMedia,i15.MatchMedia,
              [i0.NgZone]),i0.ɵmpd(4608,i16.BreakPointRegistry,i16.BreakPointRegistry,
              [i17.BREAKPOINTS]),i0.ɵmpd(4608,i18.MediaMonitor,i18.MediaMonitor,[i16.BreakPointRegistry,
              i15.MatchMedia]),i0.ɵmpd(4608,i19.ObservableMedia,i19.MediaService,[i15.MatchMedia,
              i16.BreakPointRegistry]),i0.ɵmpd(512,i4.CommonModule,i4.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i5.ɵba,i5.ɵba,([] as any[])),i0.ɵmpd(512,
              i5.ReactiveFormsModule,i5.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,
              i11.CompatibilityModule,i11.CompatibilityModule,([] as any[])),i0.ɵmpd(512,
              i6.BidiModule,i6.BidiModule,([] as any[])),i0.ɵmpd(256,i11.MATERIAL_SANITY_CHECKS,
              true,([] as any[])),i0.ɵmpd(512,i11.MdCommonModule,i11.MdCommonModule,
              [[2,i7.DOCUMENT],[2,i11.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i8.PlatformModule,
              i8.PlatformModule,([] as any[])),i0.ɵmpd(512,i9.ScrollDispatchModule,
              i9.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,i11.MdRippleModule,
              i11.MdRippleModule,([] as any[])),i0.ɵmpd(512,i11.MdPseudoCheckboxModule,
              i11.MdPseudoCheckboxModule,([] as any[])),i0.ɵmpd(512,i11.MdOptionModule,
              i11.MdOptionModule,([] as any[])),i0.ɵmpd(512,i20.PortalModule,i20.PortalModule,
              ([] as any[])),i0.ɵmpd(512,i10.OverlayModule,i10.OverlayModule,([] as any[])),
          i0.ɵmpd(512,i11.MdAutocompleteModule,i11.MdAutocompleteModule,([] as any[])),
          i0.ɵmpd(512,i11.StyleModule,i11.StyleModule,([] as any[])),i0.ɵmpd(512,i11.MdButtonModule,
              i11.MdButtonModule,([] as any[])),i0.ɵmpd(512,i11.MdButtonToggleModule,
              i11.MdButtonToggleModule,([] as any[])),i0.ɵmpd(512,i11.MdCardModule,
              i11.MdCardModule,([] as any[])),i0.ɵmpd(512,i11.MdChipsModule,i11.MdChipsModule,
              ([] as any[])),i0.ɵmpd(512,i12.ObserversModule,i12.ObserversModule,([] as any[])),
          i0.ɵmpd(512,i11.MdCheckboxModule,i11.MdCheckboxModule,([] as any[])),i0.ɵmpd(512,
              i13.A11yModule,i13.A11yModule,([] as any[])),i0.ɵmpd(512,i11.MdDialogModule,
              i11.MdDialogModule,([] as any[])),i0.ɵmpd(512,i11.MdIconModule,i11.MdIconModule,
              ([] as any[])),i0.ɵmpd(512,i11.MdDatepickerModule,i11.MdDatepickerModule,
              ([] as any[])),i0.ɵmpd(512,i21.CdkTableModule,i21.CdkTableModule,([] as any[])),
          i0.ɵmpd(512,i11.MdTableModule,i11.MdTableModule,([] as any[])),i0.ɵmpd(512,
              i11.MdExpansionModule,i11.MdExpansionModule,([] as any[])),i0.ɵmpd(512,
              i11.MdFormFieldModule,i11.MdFormFieldModule,([] as any[])),i0.ɵmpd(512,
              i11.MdLineModule,i11.MdLineModule,([] as any[])),i0.ɵmpd(512,i11.MdGridListModule,
              i11.MdGridListModule,([] as any[])),i0.ɵmpd(512,i11.MdInputModule,i11.MdInputModule,
              ([] as any[])),i0.ɵmpd(512,i11.MdListModule,i11.MdListModule,([] as any[])),
          i0.ɵmpd(512,i11.MdMenuModule,i11.MdMenuModule,([] as any[])),i0.ɵmpd(512,
              i11.MdSelectModule,i11.MdSelectModule,([] as any[])),i0.ɵmpd(512,i11.MdTooltipModule,
              i11.MdTooltipModule,([] as any[])),i0.ɵmpd(512,i11.MdPaginatorModule,
              i11.MdPaginatorModule,([] as any[])),i0.ɵmpd(512,i11.MdProgressBarModule,
              i11.MdProgressBarModule,([] as any[])),i0.ɵmpd(512,i11.MdProgressSpinnerModule,
              i11.MdProgressSpinnerModule,([] as any[])),i0.ɵmpd(512,i11.MdRadioModule,
              i11.MdRadioModule,([] as any[])),i0.ɵmpd(512,i11.MdSidenavModule,i11.MdSidenavModule,
              ([] as any[])),i0.ɵmpd(512,i11.MdSliderModule,i11.MdSliderModule,([] as any[])),
          i0.ɵmpd(512,i11.MdSlideToggleModule,i11.MdSlideToggleModule,([] as any[])),
          i0.ɵmpd(512,i11.MdSnackBarModule,i11.MdSnackBarModule,([] as any[])),i0.ɵmpd(512,
              i11.MdSortModule,i11.MdSortModule,([] as any[])),i0.ɵmpd(512,i11.MdTabsModule,
              i11.MdTabsModule,([] as any[])),i0.ɵmpd(512,i11.MdToolbarModule,i11.MdToolbarModule,
              ([] as any[])),i0.ɵmpd(512,i11.MaterialModule,i11.MaterialModule,([] as any[])),
          i0.ɵmpd(512,i22.MediaQueriesModule,i22.MediaQueriesModule,([] as any[])),
          i0.ɵmpd(512,i23.FlexLayoutModule,i23.FlexLayoutModule,([] as any[])),i0.ɵmpd(512,
              i24.SharedModule,i24.SharedModule,([] as any[])),i0.ɵmpd(512,i25.RouterModule,
              i25.RouterModule,[[2,i25.ɵa],[2,i25.Router]]),i0.ɵmpd(512,i26.LoginRoutingModule,
              i26.LoginRoutingModule,([] as any[])),i0.ɵmpd(512,i1.LoginModule,i1.LoginModule,
              ([] as any[])),i0.ɵmpd(256,i11.MD_MENU_DEFAULT_OPTIONS,{overlapTrigger:true,
              xPosition:'after',yPosition:'below'},([] as any[])),i0.ɵmpd(256,i17.BREAKPOINTS,
              i17.RAW_DEFAULTS,([] as any[])),i0.ɵmpd(1024,i25.ROUTES,() => {
            return [[{path:'login',component:i27.LoginComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWxleC9Db2RlL0phdmFTY3JpcHQvdHh0ci5pby9zcmMvYXBwL2NvcmUvbG9naW4vbG9naW4ubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FsZXgvQ29kZS9KYXZhU2NyaXB0L3R4dHIuaW8vc3JjL2FwcC9jb3JlL2xvZ2luL2xvZ2luLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
