/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['[_nghost-%COMP%] {\r\n  float: center;\r\n  margin: auto;\r\n  background: darkgrey;\r\n  padding: 10px;\r\n  width: 400px;\r\n  height: 400px;\r\n  border-radius: 10px;\r\n  border: 3px solid #478cff;\r\n  margin-top: 100px;\r\n}\r\n.actions[_ngcontent-%COMP%] {\r\n  width: 100%;\r\n}\r\n\r\nmd-divider[_ngcontent-%COMP%] {\r\n  border-width: 0.5px;\r\n  border-style: solid;\r\n  border-color: grey;\r\n}\r\n.email[_ngcontent-%COMP%] {\r\n  padding-top: 10px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWxleC9Db2RlL3R4dHIuaW8vc3JjL2FwcC9jb3JlL2xvZ2luL2xvZ2luLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FsZXgvQ29kZS90eHRyLmlvL3NyYy9hcHAvY29yZS9sb2dpbi9sb2dpbi5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
