/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.body[_ngcontent-%COMP%] {\r\n  height: 100vh;\r\n  animation: float-in-right ease 0.4s forwards;\r\n}\r\n\r\n[_nghost-%COMP%] {\r\n  display: flex;\r\n  flex: 1;\r\n  background: #363434;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWxleC9Db2RlL3R4dHIuaW8vc3JjL2FwcC9hcHAuY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvQWxleC9Db2RlL3R4dHIuaW8vc3JjL2FwcC9hcHAuY29tcG9uZW50LnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
