/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.body[_ngcontent-%COMP%] {\r\n  height: 100vh;\r\n  animation: float-in-right ease 0.4s forwards;\r\n}\r\n\r\n[_nghost-%COMP%] {\r\n  display: flex;\r\n  flex: auto;\r\n  background: #363434;\r\n}'];
//# sourceMappingURL=app.component.scss.shim.ngstyle.js.map