/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/flex-layout/flexbox/api/layout';
import * as i3 from '@angular/flex-layout/media-query/media-monitor';
import * as i4 from '@angular/flex-layout/flexbox/api/flex';
import * as i5 from '@angular/flex-layout/flexbox/api/layout-wrap';
import * as i6 from './core/toolbar/toolbar.component.ngfactory';
import * as i7 from '../../../src/app/core/toolbar/toolbar.component';
import * as i8 from '@angular/router';
import * as i9 from '../../../src/app/core/services/auth.service';
import * as i10 from '../../../src/app/app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),9,'div',[['class',
      'body'],['fxFlex',''],['fxLayout','column']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),i1.ɵdid(737280,(null as any),0,i2.LayoutDirective,
      [i3.MediaMonitor,i1.ElementRef,i1.Renderer],{layout:[0,'layout']},(null as any)),
      i1.ɵdid(737280,(null as any),0,i4.FlexDirective,[i3.MediaMonitor,i1.ElementRef,
          i1.Renderer,[3,i2.LayoutDirective],[3,i5.LayoutWrapDirective]],{flex:[0,
          'flex']},(null as any)),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),
          i1.ɵeld(0,(null as any),(null as any),1,'toolbar',([] as any[]),(null as any),
              (null as any),(null as any),i6.View_ToolbarComponent_0,i6.RenderType_ToolbarComponent)),
      i1.ɵdid(49152,(null as any),0,i7.ToolbarComponent,[i8.Router,i9.AuthService],
          (null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),
          i1.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
              (null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(212992,(null as any),0,i8.RouterOutlet,[i8.ChildrenOutletContexts,i1.ViewContainerRef,
          i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    const currVal_0:any = 'column';
    _ck(_v,1,0,currVal_0);
    const currVal_1:any = '';
    _ck(_v,2,0,currVal_1);
    _ck(_v,8,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(49152,(null as any),0,i10.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i10.AppComponent> = i1.ɵccf('app-root',
    i10.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWxleC9Db2RlL0phdmFTY3JpcHQvdHh0ci5pby9zcmMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvQWxleC9Db2RlL0phdmFTY3JpcHQvdHh0ci5pby9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9BbGV4L0NvZGUvSmF2YVNjcmlwdC90eHRyLmlvL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQWxleC9Db2RlL0phdmFTY3JpcHQvdHh0ci5pby9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImJvZHlcIiBmeExheW91dD1cImNvbHVtblwiIGZ4RmxleD5cclxuICA8dG9vbGJhcj48L3Rvb2xiYXI+XHJcbiAgPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxyXG48L2Rpdj4iLCI8YXBwLXJvb3Q+PC9hcHAtcm9vdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQUEscUNBQUE7TUFBQTthQUFBO3NCQUFBO1VBQUEsd0JBQTJDLHlDQUN6QztpQkFBQTtjQUFBO2FBQUE7VUFBQSw2QkFBbUIseUNBQ25CO2lCQUFBO2NBQUE7YUFBQTtzQ0FBQTtVQUFBLGVBQStCO0lBRmY7SUFBbEIsV0FBa0IsU0FBbEI7SUFBb0M7SUFBcEMsV0FBb0MsU0FBcEM7SUFFRTs7OztvQkNGRjtNQUFBO2FBQUE7Ozs7In0=
