/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/texts/texts-routing.module';
import * as i2 from './queued/queued.component.ngfactory';
import * as i3 from './sent/sent.component.ngfactory';
import * as i4 from './received/received.component.ngfactory';
import * as i5 from './type/type.component.ngfactory';
import * as i6 from '../../../../src/app/texts/can-activate.guard';
import * as i7 from '../../../../src/app/core/services/auth.service';
import * as i8 from '@angular/router';
import * as i9 from '../../../../src/app/texts/queued/queued.component';
import * as i10 from '../../../../src/app/texts/sent/sent.component';
import * as i11 from '../../../../src/app/texts/received/received.component';
import * as i12 from '../../../../src/app/texts/type/type.component';
export const TextsRoutingModuleNgFactory:i0.NgModuleFactory<i1.TextsRoutingModule> = i0.ɵcmf(i1.TextsRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.QueuedComponentNgFactory,i3.SentComponentNgFactory,i4.ReceivedComponentNgFactory,
              i5.TypeComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i6.CanActivateGuard,i6.CanActivateGuard,[i7.AuthService,i8.Router]),
          i0.ɵmpd(512,i8.RouterModule,i8.RouterModule,[[2,i8.ɵa],[2,i8.Router]]),i0.ɵmpd(512,
              i1.TextsRoutingModule,i1.TextsRoutingModule,([] as any[])),i0.ɵmpd(1024,
              i8.ROUTES,() => {
                return [[{path:'queued',component:i9.QueuedComponent,canActivate:[i6.CanActivateGuard]},
                    {path:'sent',component:i10.SentComponent,canActivate:[i6.CanActivateGuard]},
                    {path:'received',component:i11.ReceivedComponent,canActivate:[i6.CanActivateGuard]},
                    {path:'type',component:i12.TypeComponent,canActivate:[i6.CanActivateGuard]}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWxleC9Db2RlL0phdmFTY3JpcHQvdHh0ci5pby9zcmMvYXBwL3RleHRzL3RleHRzLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FsZXgvQ29kZS9KYXZhU2NyaXB0L3R4dHIuaW8vc3JjL2FwcC90ZXh0cy90ZXh0cy1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
