/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../src/app/texts/received/received.component';
const styles_ReceivedComponent:any[] = ([] as any[]);
export const RenderType_ReceivedComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ReceivedComponent,data:{}});
export function View_ReceivedComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['Received Component']))],(null as any),
      (null as any));
}
export function View_ReceivedComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_ReceivedComponent_0,
      RenderType_ReceivedComponent)),i0.ɵdid(114688,(null as any),0,i1.ReceivedComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ReceivedComponentNgFactory:i0.ComponentFactory<i1.ReceivedComponent> = i0.ɵccf('ng-component',
    i1.ReceivedComponent,View_ReceivedComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWxleC9Db2RlL0phdmFTY3JpcHQvdHh0ci5pby9zcmMvYXBwL3RleHRzL3JlY2VpdmVkL3JlY2VpdmVkLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9BbGV4L0NvZGUvSmF2YVNjcmlwdC90eHRyLmlvL3NyYy9hcHAvdGV4dHMvcmVjZWl2ZWQvcmVjZWl2ZWQuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvQWxleC9Db2RlL0phdmFTY3JpcHQvdHh0ci5pby9zcmMvYXBwL3RleHRzL3JlY2VpdmVkL3JlY2VpdmVkLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQWxleC9Db2RlL0phdmFTY3JpcHQvdHh0ci5pby9zcmMvYXBwL3RleHRzL3JlY2VpdmVkL3JlY2VpdmVkLmNvbXBvbmVudC50cy5SZWNlaXZlZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlJlY2VpdmVkIENvbXBvbmVudCIsIjxuZy1jb21wb25lbnQ+PC9uZy1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7Ozs7b0JDQUE7TUFBQTtrQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
